<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
            <title>Milenio</title>
        </head>
        <nav class="navbar bg-body-tertiary px-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="?action=home">
                    <img src="../images/logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                    Milenio
                </a>
                <a href="../router.php/?action=login"><button type="button" class="btn btn-primary">Login</button></a>
            </div>
        </nav>
        <body>
    