<?php require 'templates/layout/header.phtml'; ?>

<div class="d-flex justify-content-center mt-4">
    <div class="card" style="width: 90%;">
        <div class="card-body">
            <h4 class="card-title mb-3 fw-bold"><?php echo $libro->nombre; ?></h4>
            <h6 class="card-subtitle mb-2 text-body-secondary"><?php echo $libro->autor; ?></h6>
            <p class="card-text"><?php echo $libro->resena; ?></p>
            <span class="badge bg-info"><?php echo $libro->genero; ?></span>
            <div class="mt-3">
                <a href="#" class="card-link btn btn-primary">Editar</a>
                <a href="#" class="card-link btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml'; ?>
