<?php 
    require 'templates/layout/header.phtml' ;
    include_once './app/models/catalogo.model.php';
?>

<div class="container-sm mt-5">
    <h2 class="fs-3 fw-bold mt-5 mb-3">Editar libro</h2>
    <form class="mb-5">
    <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input type="text" class="form-control" name="nombre"> 
    </div>
    <div class="mb-3">
        <label class="form-label">Autor</label>
        <input type="text" class="form-control" name="autor"> 
    </div>
    <?php
        echo '<label class="form-label">Categoria</label>';
        echo '<select class="form-select mb-3" aria-label="Default select example" name="categoria">';
        echo '<option selected>Seleccione una categoria</option>';
        foreach ($generos as $genero) {
            echo '<option value="' . $genero. '">' . $genero. '</option>';    }

        echo '</select>';
    ?>
    <div class="mb-3">
        <label class="form-label">Reseña</label>
        <textarea class="form-control" name="resena" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
</div>

<?php require 'templates/layout/footer.phtml' ?>

