<html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
            <title>Milenio</title>
        </head>
        <nav class="navbar bg-body-tertiary px-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="../router.php/?action=home">
                    <img src="../images/logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                    Milenio
                </a>
            </div>
        </nav>
    <body>
        <div class="container-sm mt-5">
            <form>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <button type="submit" class="btn btn-primary">Iniciar sesion</button>
            </form> 
        </div>

