<html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
            <title>Milenio</title>
        </head>
        <nav class="navbar bg-body-tertiary px-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="home">
                <img src="<?php echo BASE_URL; ?>images/logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                    Milenio
                </a>
            </div>
        </nav>
    <body>
    <body>
    <div class="container-sm mt-5">
        <form method="POST" action="login">
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" name="email" class="form-control" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form> 
        <?php if ($error): ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>
    </div>

<?php require 'templates/layout/footer.phtml' ?>
    

