<?php 
    require 'templates/layout/header.phtml' ;
    include_once './app/models/genero.model.php';
?>
<div class="container-sm mt-5">
    <h2 class="fs-3 fw-bold mt-5 mb-3">Editar libro</h2>
    <form method="POST" action="<?= BASE_URL ?>editar-libro/<?= $libro->id ?>">
        <div class="mb-3">
            <label class="form-label">Nombre</label>
            <input type="text" class="form-control" name="titulo" value="<?= $libro->titulo ?>"> 
        </div>
        <div class="mb-3">
            <label class="form-label">Autor</label>
            <input type="text" class="form-control" name="autor" value="<?= $libro->autor ?>"> 
        </div>
        <div class="mb-3">
            <label class="form-label">Categoría</label>
            <select class="form-select mb-3" name="genero_id">
                <option selected><?= $libro->genero_nombre ?></option>
                <?php 
                    foreach ($generos as $genero){
                        echo '<option value="' . $genero->id. '">' . $genero->nombre. '</option>';
                    }
                ?>
            </select>        
        </div>
        <div class="mb-3">
            <label class="form-label">Reseña</label>
            <textarea class="form-control" name="reseña" rows="3"><?= $libro->reseña ?></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
</div>
