<?php 
    require 'templates/layout/header.phtml' ;
    include_once './app/models/genero.model.php';
?>
<div class="container-sm mt-5">
    <h2 class="fs-3 fw-bold mt-5 mb-3">Editar genero</h2>
    <form method="POST" action="<?= BASE_URL ?>editar-genero/<?= $genero->id ?>">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre del Género</label>
            <input type="text" class="form-control" name="nombre" value="<?= $genero->nombre ?>" required>
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <textarea class="form-control" name="descripcion" rows="3"><?= $genero->descripcion ?></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
    </form>
</div>
