<?php
include_once './app/models/genero.model.php';
?>

<?php if (isset($_SESSION['email'])): ?>
    <div class="mx-5 mt-5">
        <h2 class="fs-3 fw-bold mb-4">Administrar catalogo</h2>
        <ul class="nav justify-content-start d-inline-flex gap-3">
            <a href="addCatalogo"><button type="button" class="btn btn-primary">Agregar Genero</button></a>
            <a href="addCatalogo"><button type="button" class="btn btn-primary">Agregar Libro</button></a>
        </ul>
    </div>
<?php endif; ?>

<h2 class="fs-3 fw-bold mt-5 ms-5">Generos</h2>
<ul class="nav justify-content-start ms-5 mt-4 d-inline-flex gap-3">
    <li class="nav-item">
        <a href="home"><button type="button" class="btn btn-outline-primary">Ver Todos</button></a>
    </li>
    <?php foreach ($generos as $genero): ?>
        <li class="nav-item">
            <a href="home?genero=<?= urlencode($genero->nombre) ?>">
                <button type="button" class="btn btn-outline-primary">
                    <?php echo $genero->nombre ?>
                </button>
            </a>
        </li>
    <?php endforeach; ?>
</ul>
<?php if ($generoDetalle): ?>
    <div class="ms-4">
        <div class="p-4">
            <h3 class="fs-4 fw-bold text-primary"><?php echo $generoDetalle->nombre; ?></h3>
            <p class="text-muted"><?php echo $generoDetalle->descripcion; ?></p>
            <?php if (isset($_SESSION['email'])): ?>
                <div class="mt-3">
                    <a href="editar-genero/<?= $generoDetalle->id ?>" class="btn btn-outline-primary">Editar</a>
                    <form action="eliminar-genero" method="POST" style="display:inline;">
                        <input type="hidden" name="id" value="<?php echo $generoDetalle->id; ?>">
                        <button type="submit" class="btn btn-outline-danger">Eliminar</button>
                    </form>          
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

