<?php require 'templates/layout/header.phtml' ?>

<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
    <i class="bi bi-exclamation-triangle-fill text-danger" style="font-size: 4rem;"></i>
        <h1 class="display-1 font-weight-bold">404 NOT FOUND</h1>
        <p class="h3 text-body-secondary mb-3">Oops! La pagina que buscas no se pudo encontrar!</p>
        <a href="?action=home" class="btn btn-primary mt-5">Volver al inicio</a>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>
