<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="<?php echo BASE_URL ?>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
        <title>Milenio</title>
    </head>
    <nav class="navbar bg-body-tertiary px-3">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="home">
            <img src="<?php echo BASE_URL; ?>images/logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
                Milenio
            </a>
            <?php if(isset($_SESSION['email'])): ?>
                <span class="navbar-text"><?= $_SESSION['email'] ?></span>
                <a href="logout"><button type="button" class="btn btn-secondary">Logout</button></a>
            <?php else: ?>
                <a href="showLogin"><button type="button" class="btn btn-primary">Login</button></a>
            <?php endif; ?>
        </div>
    </nav>
<body>

    